scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser_frame
    min_x: -0.3
    max_x: 0.3
    min_y: -0.2
    max_y: 0.2
    min_z: -1.0
    max_z: 1.0